name: co2kernel_16_build
on:
  workflow_dispatch:
    inputs:
      KERNEL_NAME:
        description: "自定义 Linux version"
        required: true
        default: "-android13-8-o-01154-gf7540e130d00"
      UTS_VERSION:
        description: "自定义 UTS_VERSION 时间戳"
        required: true
        default: "#1 SMP PREEMPT Thu Oct 23 16:30:45 UTC 2025"
      DMESG_BUFFER_2M:
        type: boolean
        description: "启用 2M dmesg 缓冲区"
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Configure Git
        run: |
          git config --global user.name "DogEZ"
          git config --global user.email "DdogezD@gmail.com"

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/co2kernel/kernel_manifest.git -b refs/heads/oneplus/sm8550 -m oneplus_open_b.xml --depth=1
          repo sync

      - name: Setup overwriter
        run: |
          cd kernel_workspace/kernel_platform/common
          chmod +x ./drivers/of/overwriter/overwrite_configs/convert_configs.sh
          ./drivers/of/overwriter/overwrite_configs/convert_configs.sh
          rm -rf ./drivers/of/overwriter/overwrite_configs
          rm -rf ./drivers/of/overwriter/tools
          rm -f ./drivers/of/overwriter/README.md

      - name: Add Debug flavors
        run: |
          cd kernel_workspace/kernel_platform/common
          if [ "${{ fromJSON(github.event.inputs.DMESG_BUFFER_2M) }}" = "true" ]; then
              echo "CONFIG_LOG_BUF_SHIFT=21" >> "./common/arch/arm64/configs/gki_defconfig"
          fi

      - name: Spoof Linux version
        run: |
          cd kernel_workspace/kernel_platform
          sed -i '$s|echo "\$res"|echo "\${{ github.event.inputs.KERNEL_NAME }}"|' ./common/scripts/setlocalversion
          sed -i '/UTS_VERSION=.*cut -b -\$UTS_LEN)/s#UTS_VERSION=.*#UTS_VERSION="\${{ github.event.inputs.UTS_VERSION }}"#' ./common/scripts/mkcompile_h

      - name: Build kernel
        run: |
          cd kernel_workspace
          LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh kalama gki

      - name: Make AnyKernel3
        run: |
         git clone https://github.com/co2kernel/AnyKernel3 --depth=1
         rm -rf ./AnyKernel3/.git
         cp kernel_workspace/kernel_platform/out/msm-kernel-kalama-gki/dist/Image ./AnyKernel3/

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: co2kernel_ak3
         path: ./AnyKernel3/*

      - name: Upload kernel image
        uses: actions/upload-artifact@v4
        with:
         name: co2kernel
         path: kernel_workspace/kernel_platform/out/msm-kernel-kalama-gki/dist/Image
